//
//  LocalizationManager.swift
//  PDFSignature
//

import Combine
import Foundation
import SwiftUI

public enum AppLanguage: String, CaseIterable, Identifiable, Codable, Hashable {
    case en = "en"
    case es = "es"
    case fr = "fr"
    case de = "de"
    case it = "it"
    case pt = "pt"
    case ja = "ja"
    case zhHans = "zh-Hans"
    case ar = "ar"
    case hi = "hi"

    public var id: String { rawValue }

    public var code: String { rawValue }

    public var flag: String {
        switch self {
        case .en: return "🇺🇸"
        case .es: return "🇪🇸"
        case .fr: return "🇫🇷"
        case .de: return "🇩🇪"
        case .it: return "🇮🇹"
        case .pt: return "🇵🇹"
        case .ja: return "🇯🇵"
        case .zhHans: return "🇨🇳"
        case .ar: return "🇸🇦"
        case .hi: return "🇮🇳"
        }
    }

    public var nativeTitle: String {
        switch self {
        case .en: return "English"
        case .es: return "Español"
        case .fr: return "Français"
        case .de: return "Deutsch"
        case .it: return "Italiano"
        case .pt: return "Português"
        case .ja: return "日本語"
        case .zhHans: return "简体中文"
        case .ar: return "العربية"
        case .hi: return "हिन्दी"
        }
    }

    public var englishTitle: String {
        switch self {
        case .en: return "English"
        case .es: return "Spanish"
        case .fr: return "French"
        case .de: return "German"
        case .it: return "Italian"
        case .pt: return "Portuguese"
        case .ja: return "Japanese"
        case .zhHans: return "Chinese (Simplified)"
        case .ar: return "Arabic"
        case .hi: return "Hindi"
        }
    }

    public var layoutDirection: LayoutDirection {
        switch self {
        case .ar: return .rightToLeft
        default: return .leftToRight
        }
    }
}

@MainActor
public final class LocalizationManager: ObservableObject {
    public static let shared = LocalizationManager()

    @AppStorage("app_language") private var savedLanguageCode: String = AppLanguage.en.rawValue

    @Published public private(set) var currentLanguage: AppLanguage = .en

    private var cachedBundle: Bundle?

    private init() {
        if let stored = AppLanguage(rawValue: savedLanguageCode) {
            self.currentLanguage = stored
        } else {
            let preferred = Locale.preferredLanguages.first ?? "en"
            let matching = AppLanguage.allCases.first { preferred.hasPrefix($0.code) } ?? .en
            self.currentLanguage = matching
            self.savedLanguageCode = matching.rawValue
        }
        updateBundle()
    }

    public func setLanguage(_ language: AppLanguage) {
        guard language != currentLanguage else { return }
        currentLanguage = language
        savedLanguageCode = language.rawValue
        updateBundle()
        objectWillChange.send()
        HapticFeedback.selection()
    }

    private func updateBundle() {
        if let path = Bundle.main.path(forResource: currentLanguage.code, ofType: "lproj"),
           let bundle = Bundle(path: path) {
            cachedBundle = bundle
        } else {
            cachedBundle = nil
        }
    }

    public func localized(_ key: String, _ args: CVarArg...) -> String {
        var format: String?
        if let bundle = cachedBundle {
            format = bundle.localizedString(forKey: key, value: nil, table: nil)
            if format == key {
                format = nil
            }
        }

        if format == nil {
            format = LocalizationDictionary.table[currentLanguage]?[key]
                ?? LocalizationDictionary.table[.en]?[key]
                ?? key
        }

        let rawFormat = format ?? key
        if args.isEmpty {
            return rawFormat
        } else {
            return String(format: rawFormat, arguments: args)
        }
    }
}

// MARK: - Global Convenience Helper
public func L10n(_ key: String, _ args: CVarArg...) -> String {
    LocalizationManager.shared.localized(key, args)
}

public extension String {
    var localized: String {
        LocalizationManager.shared.localized(self)
    }

    func localized(with args: CVarArg...) -> String {
        LocalizationManager.shared.localized(self, args)
    }
}

// MARK: - In-Memory Localization Dictionary for Guaranteed Reliability
private enum LocalizationDictionary {
    static let table: [AppLanguage: [String: String]] = [
        .en: [
            "home": "Home",
            "history": "History",
            "settings": "Settings",
            "signatures": "Signatures",
            "new_signature": "New Signature",
            "save": "Save",
            "cancel": "Cancel",
            "done": "Done",
            "close": "Close",
            "delete": "Delete",
            "clear": "Clear",
            "undo": "Undo",
            "edit": "Edit",
            "rename": "Rename",
            "search": "Search",
            "apply": "Apply",
            "skip": "Skip",
            "continue": "Continue",
            "get_started": "Get Started",
            "error": "Error",
            "ok": "OK",
            "hello": "Hello",
            "home_subtitle": "Import a PDF and sign in seconds.",
            "search_signed_docs": "Search signed documents",
            "see_all": "See all",
            "add_new_signature": "Add New Signature",
            "recent_signed": "Recent signed",
            "recent": "Recent",
            "see_more": "See more",
            "no_signed_docs": "No signed documents yet",
            "sign_first_doc": "Sign your first document to see it here.",
            "quick_sign_banner_title": "Quick Sign",
            "quick_sign_banner_subtitle": "Select a PDF from Files to sign",
            "import_pdf": "Import PDF",
            "draw": "Draw",
            "type": "Type",
            "scan_photo": "Photo / Scan",
            "signature_name": "Signature name",
            "signature_color": "Signature color",
            "stroke_size": "Stroke size",
            "type_your_signature": "Type your name or initials",
            "choose_font_style": "Font Style",
            "pick_from_photos": "Photo Library",
            "take_photo": "Take Photo",
            "remove_background": "Remove Background",
            "bg_removed_auto": "Clean Transparent Signature",
            "bg_sensitivity": "Sensitivity",
            "original_photo": "Original",
            "transparent_signature": "Isolated Ink",
            "ink_color": "Ink color",
            "no_signatures_yet": "No signatures yet",
            "create_signature_desc": "Tap the '+' button above to create one.",
            "choose_signature": "Choose signature",
            "choose_signature_picker": "Signature",
            "rename_signature": "Rename signature",
            "rename_signature_desc": "Give this signature a memorable name.",
            "sign_pdf": "Sign PDF",
            "page_x_of_y": "Page %d / %d",
            "undo_last": "Undo last",
            "apply_to_page": "Apply to page",
            "signature_size": "Size",
            "signature_size_label": "Size",
            "resize": "Resize",
            "resize_hint": "Drag corner handle or pinch signature to resize",
            "document_title": "Signed Document Title",
            "save_signed_pdf": "Save signed PDF",
            "saving": "Saving…",
            "open_preview": "Open preview",
            "signing_instructions": "Position the sticker, then tap Apply to page to lock it on this page preview.",
            "search_signed_pdfs": "Search signed PDFs",
            "no_history_yet": "No history yet",
            "history_empty_subtitle": "Signed documents will appear here in a clean timeline.",
            "delete_pdf_title": "Delete Signed PDF?",
            "delete_pdf_message": "This action cannot be undone.",
            "pages": "pages",
            "page": "page",
            "share": "Share",
            "appearance": "Appearance",
            "theme_system": "System",
            "theme_light": "Light",
            "theme_dark": "Dark",
            "preferences": "Preferences",
            "language": "Language",
            "select_language": "Select Language",
            "search_language": "Search language",
            "icloud_library": "iCloud library",
            "sync_with_icloud": "Sync library with iCloud",
            "last_icloud_activity": "Last iCloud activity: %@",
            "sync_now": "Sync now",
            "sync_pending": "Sync pending…",
            "spread_word": "Spread the word",
            "share_app": "Share App",
            "rate_app": "Rate App",
            "support": "Support",
            "privacy_policy": "Privacy Policy",
            "terms_of_use": "Terms of Use",
            "contact_support": "Contact Support",
            "feedback": "Feedback",
            "about": "About",
            "version": "Version",
            "tagline": "E-Sign PDF & Document Manager",
            "all_features_ready": "All Features Ready",
            "my_signatures": "My Signatures",
            "create_signature": "Create Signature",
            "preview_signature": "Signature Preview",
            "share_png": "Share PNG",
            "save_to_photos": "Save to Photos",
            "saved_to_photos_success": "Saved to Photos with clear background!",
            "transparent_png": "Transparent PNG",
            "full_screen_preview": "Full Screen Preview",
            "app_title": "PDF Signature",
            "preview": "Preview"
        ],
        .es: [
            "home": "Inicio",
            "history": "Historial",
            "settings": "Ajustes",
            "signatures": "Firmas",
            "new_signature": "Nueva firma",
            "save": "Guardar",
            "cancel": "Cancelar",
            "done": "Listo",
            "close": "Cerrar",
            "delete": "Eliminar",
            "clear": "Borrar",
            "undo": "Deshacer",
            "edit": "Editar",
            "rename": "Renombrar",
            "search": "Buscar",
            "apply": "Aplicar",
            "skip": "Omitir",
            "continue": "Continuar",
            "get_started": "Empezar",
            "error": "Error",
            "ok": "Aceptar",
            "hello": "Hola",
            "home_subtitle": "Importa un PDF y firma en segundos.",
            "search_signed_docs": "Buscar documentos firmados",
            "see_all": "Ver todo",
            "add_new_signature": "Agregar nueva firma",
            "recent_signed": "Firmados recientemente",
            "recent": "Recientes",
            "see_more": "Ver más",
            "no_signed_docs": "No hay documentos firmados aún",
            "sign_first_doc": "Firma tu primer documento para verlo aquí.",
            "quick_sign_banner_title": "Firma rápida",
            "quick_sign_banner_subtitle": "Selecciona un PDF desde Archivos para firmar",
            "import_pdf": "Importar PDF",
            "draw": "Dibujar",
            "type": "Escribir",
            "scan_photo": "Foto / Escáner",
            "signature_name": "Nombre de la firma",
            "signature_color": "Color de la firma",
            "stroke_size": "Grosor del trazo",
            "type_your_signature": "Escribe tu nombre o iniciales",
            "choose_font_style": "Estilo de fuente",
            "pick_from_photos": "Galería de fotos",
            "take_photo": "Tomar foto",
            "remove_background": "Eliminar fondo",
            "bg_removed_auto": "Firma transparente limpia",
            "bg_sensitivity": "Sensibilidad",
            "original_photo": "Original",
            "transparent_signature": "Tinta aislada",
            "ink_color": "Color de tinta",
            "no_signatures_yet": "No hay firmas aún",
            "create_signature_desc": "Toca el botón '+' arriba para crear una.",
            "choose_signature": "Elegir firma",
            "choose_signature_picker": "Firma",
            "rename_signature": "Renombrar firma",
            "rename_signature_desc": "Asigna un nombre memorable a esta firma.",
            "sign_pdf": "Firmar PDF",
            "page_x_of_y": "Página %d / %d",
            "undo_last": "Deshacer último",
            "apply_to_page": "Aplicar a página",
            "signature_size": "Tamaño",
            "signature_size_label": "Tamaño",
            "resize": "Redimensionar",
            "resize_hint": "Arrastra la esquina o pellizca la firma para redimensionar",
            "document_title": "Título del documento firmado",
            "save_signed_pdf": "Guardar PDF firmado",
            "saving": "Guardando…",
            "open_preview": "Abrir vista previa",
            "signing_instructions": "Ubica la firma y toca Aplicar para fijarla en esta página.",
            "search_signed_pdfs": "Buscar PDFs firmados",
            "no_history_yet": "Sin historial aún",
            "history_empty_subtitle": "Tus documentos firmados aparecerán aquí.",
            "delete_pdf_title": "¿Eliminar PDF firmado?",
            "delete_pdf_message": "Esta acción no se puede deshacer.",
            "pages": "páginas",
            "page": "página",
            "share": "Compartir",
            "appearance": "Apariencia",
            "theme_system": "Sistema",
            "theme_light": "Claro",
            "theme_dark": "Oscuro",
            "preferences": "Preferencias",
            "language": "Idioma",
            "select_language": "Seleccionar idioma",
            "search_language": "Buscar idioma",
            "icloud_library": "Biblioteca iCloud",
            "sync_with_icloud": "Sincronizar con iCloud",
            "last_icloud_activity": "Última actividad en iCloud: %@",
            "sync_now": "Sincronizar ahora",
            "sync_pending": "Sincronización pendiente…",
            "spread_word": "Compartir",
            "share_app": "Compartir aplicación",
            "rate_app": "Calificar aplicación",
            "support": "Soporte",
            "privacy_policy": "Política de privacidad",
            "terms_of_use": "Términos de uso",
            "contact_support": "Contactar soporte",
            "feedback": "Comentarios",
            "about": "Acerca de",
            "version": "Versión",
            "tagline": "E-Sign PDF y Gestor de Documentos",
            "all_features_ready": "Todas las funciones listas",
            "my_signatures": "Mis firmas",
            "create_signature": "Crear firma"
        ],
        .fr: [
            "home": "Accueil",
            "history": "Historique",
            "settings": "Paramètres",
            "signatures": "Signatures",
            "new_signature": "Nouvelle signature",
            "save": "Enregistrer",
            "cancel": "Annuler",
            "done": "Terminé",
            "close": "Fermer",
            "delete": "Supprimer",
            "clear": "Effacer",
            "undo": "Annuler",
            "edit": "Modifier",
            "rename": "Renommer",
            "search": "Rechercher",
            "apply": "Appliquer",
            "skip": "Passer",
            "continue": "Continuer",
            "get_started": "Commencer",
            "error": "Erreur",
            "ok": "OK",
            "hello": "Bonjour",
            "home_subtitle": "Importez un PDF et signez en quelques secondes.",
            "search_signed_docs": "Rechercher des documents signés",
            "see_all": "Voir tout",
            "add_new_signature": "Ajouter une nouvelle signature",
            "recent_signed": "Signés récemment",
            "recent": "Récents",
            "see_more": "Voir plus",
            "no_signed_docs": "Aucun document signé pour le moment",
            "sign_first_doc": "Signez votre premier document pour le voir ici.",
            "quick_sign_banner_title": "Signature rapide",
            "quick_sign_banner_subtitle": "Sélectionnez un PDF depuis Fichiers pour signer",
            "import_pdf": "Importer un PDF",
            "draw": "Dessiner",
            "type": "Taper",
            "scan_photo": "Photo / Scanner",
            "signature_name": "Nom de la signature",
            "signature_color": "Couleur de la signature",
            "stroke_size": "Épaisseur du trait",
            "type_your_signature": "Tapez votre nom ou vos initiales",
            "choose_font_style": "Style de police",
            "pick_from_photos": "Photothèque",
            "take_photo": "Prendre une photo",
            "remove_background": "Supprimer l'arrière-plan",
            "bg_removed_auto": "Signature transparente propre",
            "bg_sensitivity": "Sensibilité",
            "original_photo": "Original",
            "transparent_signature": "Encre isolée",
            "ink_color": "Couleur de l'encre",
            "no_signatures_yet": "Aucune signature",
            "create_signature_desc": "Appuyez sur '+' en haut pour en créer une.",
            "choose_signature": "Choisir une signature",
            "choose_signature_picker": "Signature",
            "rename_signature": "Renommer la signature",
            "rename_signature_desc": "Donnez un nom mémorable à cette signature.",
            "sign_pdf": "Signer le PDF",
            "page_x_of_y": "Page %d / %d",
            "undo_last": "Annuler le dernier",
            "apply_to_page": "Appliquer à la page",
            "signature_size": "Taille",
            "signature_size_label": "Taille",
            "resize": "Redimensionner",
            "resize_hint": "Glissez le coin ou pincez la signature pour redimensionner",
            "document_title": "Titre du document signé",
            "save_signed_pdf": "Enregistrer le PDF signé",
            "saving": "Enregistrement…",
            "open_preview": "Ouvrir l'aperçu",
            "signing_instructions": "Positionnez la signature et appuyez sur Appliquer pour la verrouiller.",
            "search_signed_pdfs": "Rechercher des PDF signés",
            "no_history_yet": "Aucun historique",
            "history_empty_subtitle": "Vos documents signés s'afficheront ici.",
            "delete_pdf_title": "Supprimer le PDF signé ?",
            "delete_pdf_message": "Cette action est irréversible.",
            "pages": "pages",
            "page": "page",
            "share": "Partager",
            "appearance": "Apparence",
            "theme_system": "Système",
            "theme_light": "Clair",
            "theme_dark": "Sombre",
            "preferences": "Préférences",
            "language": "Langue",
            "select_language": "Sélectionner la langue",
            "search_language": "Rechercher une langue",
            "icloud_library": "Bibliothèque iCloud",
            "sync_with_icloud": "Synchroniser avec iCloud",
            "last_icloud_activity": "Dernière activité iCloud : %@",
            "sync_now": "Synchroniser maintenant",
            "sync_pending": "Synchronisation en attente…",
            "spread_word": "Partager",
            "share_app": "Partager l'application",
            "rate_app": "Évaluer l'application",
            "support": "Assistance",
            "privacy_policy": "Politique de confidentialité",
            "terms_of_use": "Conditions d'utilisation",
            "contact_support": "Contacter l'assistance",
            "feedback": "Commentaires",
            "about": "À propos",
            "version": "Version",
            "tagline": "E-Sign PDF & Gestionnaire de documents",
            "all_features_ready": "Toutes les fonctions disponibles",
            "my_signatures": "Mes signatures",
            "create_signature": "Créer une signature"
        ],
        .de: [
            "home": "Startseite",
            "history": "Verlauf",
            "settings": "Einstellungen",
            "signatures": "Signaturen",
            "new_signature": "Neue Signatur",
            "save": "Speichern",
            "cancel": "Abbrechen",
            "done": "Fertig",
            "close": "Schließen",
            "delete": "Löschen",
            "clear": "Löschen",
            "undo": "Rückgängig",
            "edit": "Bearbeiten",
            "rename": "Umbenennen",
            "search": "Suchen",
            "apply": "Anwenden",
            "skip": "Überspringen",
            "continue": "Weiter",
            "get_started": "Loslegen",
            "error": "Fehler",
            "ok": "OK",
            "hello": "Hallo",
            "home_subtitle": "PDF importieren und in Sekunden signieren.",
            "search_signed_docs": "Signierte Dokumente durchsuchen",
            "see_all": "Alle ansehen",
            "add_new_signature": "Neue Signatur hinzufügen",
            "recent_signed": "Kürzlich signiert",
            "recent": "Zuletzt",
            "see_more": "Mehr sehen",
            "no_signed_docs": "Noch keine signierten Dokumente",
            "sign_first_doc": "Signieren Sie Ihr erstes Dokument.",
            "quick_sign_banner_title": "Schnell signieren",
            "quick_sign_banner_subtitle": "PDF aus Dateien auswählen und signieren",
            "import_pdf": "PDF importieren",
            "draw": "Zeichnen",
            "type": "Tippen",
            "scan_photo": "Foto / Scannen",
            "signature_name": "Signaturname",
            "signature_color": "Signaturfarbe",
            "stroke_size": "Strichstärke",
            "type_your_signature": "Namen oder Initialen eingeben",
            "choose_font_style": "Schriftstil",
            "pick_from_photos": "Fotogalerie",
            "take_photo": "Foto aufnehmen",
            "remove_background": "Hintergrund entfernen",
            "bg_removed_auto": "Transparente Signatur",
            "bg_sensitivity": "Empfindlichkeit",
            "original_photo": "Original",
            "transparent_signature": "Isolierte Tinte",
            "ink_color": "Tintenfarbe",
            "no_signatures_yet": "Noch keine Signaturen",
            "create_signature_desc": "Tippen Sie oben auf '+', um eine zu erstellen.",
            "choose_signature": "Signatur wählen",
            "choose_signature_picker": "Signatur",
            "rename_signature": "Signatur umbenennen",
            "rename_signature_desc": "Geben Sie einen Namen ein.",
            "sign_pdf": "PDF signieren",
            "page_x_of_y": "Seite %d / %d",
            "undo_last": "Letztes rückgängig",
            "apply_to_page": "Auf Seite anwenden",
            "signature_size": "Größe",
            "signature_size_label": "Größe",
            "resize": "Größe ändern",
            "resize_hint": "Ecke ziehen oder zusammenziehen zum Ändern",
            "document_title": "Titel des Dokuments",
            "save_signed_pdf": "Signiertes PDF speichern",
            "saving": "Wird gespeichert…",
            "open_preview": "Vorschau öffnen",
            "signing_instructions": "Platzieren Sie die Signatur und tippen Sie auf Anwenden.",
            "search_signed_pdfs": "Signierte PDFs suchen",
            "no_history_yet": "Noch kein Verlauf",
            "history_empty_subtitle": "Signierte Dokumente werden hier angezeigt.",
            "delete_pdf_title": "Signiertes PDF löschen?",
            "delete_pdf_message": "Dies kann nicht rückgängig gemacht werden.",
            "pages": "Seiten",
            "page": "Seite",
            "share": "Teilen",
            "appearance": "Erscheinungsbild",
            "theme_system": "System",
            "theme_light": "Hell",
            "theme_dark": "Dunkel",
            "preferences": "Präferenzen",
            "language": "Sprache",
            "select_language": "Sprache auswählen",
            "search_language": "Sprache suchen",
            "icloud_library": "iCloud-Mediathek",
            "sync_with_icloud": "Mit iCloud synchronisieren",
            "last_icloud_activity": "Letzte iCloud-Aktivität: %@",
            "sync_now": "Jetzt synchronisieren",
            "sync_pending": "Synchronisierung ausstehend…",
            "spread_word": "Weitersagen",
            "share_app": "App teilen",
            "rate_app": "App bewerten",
            "support": "Support",
            "privacy_policy": "Datenschutzerklärung",
            "terms_of_use": "Nutzungsbedingungen",
            "contact_support": "Support kontaktieren",
            "feedback": "Feedback",
            "about": "Über",
            "version": "Version",
            "tagline": "E-Sign PDF & Dokumentenmanager",
            "all_features_ready": "Alle Funktionen freigeschaltet",
            "my_signatures": "Meine Signaturen",
            "create_signature": "Signatur erstellen"
        ],
        .it: [
            "home": "Home",
            "history": "Cronologia",
            "settings": "Impostazioni",
            "signatures": "Firme",
            "new_signature": "Nuova firma",
            "save": "Salva",
            "cancel": "Annulla",
            "done": "Fatto",
            "close": "Chiudi",
            "delete": "Elimina",
            "clear": "Cancella",
            "undo": "Annulla",
            "edit": "Modifica",
            "rename": "Rinomina",
            "search": "Cerca",
            "apply": "Applica",
            "skip": "Salta",
            "continue": "Continua",
            "get_started": "Inizia",
            "error": "Errore",
            "ok": "OK",
            "hello": "Ciao",
            "home_subtitle": "Importa un PDF e firma in pochi secondi.",
            "search_signed_docs": "Cerca documenti firmati",
            "see_all": "Vedi tutti",
            "add_new_signature": "Aggiungi nuova firma",
            "recent_signed": "Firmati di recente",
            "recent": "Recenti",
            "see_more": "Vedi altro",
            "no_signed_docs": "Nessun documento firmato",
            "sign_first_doc": "Firma il tuo primo documento.",
            "quick_sign_banner_title": "Firma rapida",
            "quick_sign_banner_subtitle": "Seleziona un PDF da File da firmare",
            "import_pdf": "Importa PDF",
            "draw": "Disegna",
            "type": "Digita",
            "scan_photo": "Foto / Scansione",
            "signature_name": "Nome firma",
            "signature_color": "Colore firma",
            "stroke_size": "Spessore tratto",
            "type_your_signature": "Digita nome o iniziali",
            "choose_font_style": "Stile carattere",
            "pick_from_photos": "Libreria foto",
            "take_photo": "Scatta foto",
            "remove_background": "Rimuovi sfondo",
            "bg_removed_auto": "Firma trasparente nitida",
            "bg_sensitivity": "Sensibilità",
            "original_photo": "Originale",
            "transparent_signature": "Inchiostro isolato",
            "ink_color": "Colore inchiostro",
            "no_signatures_yet": "Nessuna firma",
            "create_signature_desc": "Tocca '+' in alto per crearne una.",
            "choose_signature": "Scegli firma",
            "choose_signature_picker": "Firma",
            "rename_signature": "Rinomina firma",
            "rename_signature_desc": "Assegna un nome a questa firma.",
            "sign_pdf": "Firma PDF",
            "page_x_of_y": "Pagina %d / %d",
            "undo_last": "Annulla ultimo",
            "apply_to_page": "Applica alla pagina",
            "signature_size": "Dimensione",
            "signature_size_label": "Dimensione",
            "resize": "Ridimensiona",
            "resize_hint": "Trascina l'angolo o pizzica per ridimensionare",
            "document_title": "Titolo documento firmato",
            "save_signed_pdf": "Salva PDF firmato",
            "saving": "Salvataggio…",
            "open_preview": "Apri anteprima",
            "signing_instructions": "Posiziona la firma e tocca Applica per fissarla.",
            "search_signed_pdfs": "Cerca PDF firmati",
            "no_history_yet": "Nessuna cronologia",
            "history_empty_subtitle": "I documenti firmati appariranno qui.",
            "delete_pdf_title": "Eliminare PDF firmato?",
            "delete_pdf_message": "Questa azione non può essere annullata.",
            "pages": "pagine",
            "page": "pagina",
            "share": "Condividi",
            "appearance": "Aspetto",
            "theme_system": "Sistema",
            "theme_light": "Chiaro",
            "theme_dark": "Scuro",
            "preferences": "Preferenze",
            "language": "Lingua",
            "select_language": "Seleziona lingua",
            "search_language": "Cerca lingua",
            "icloud_library": "Libreria iCloud",
            "sync_with_icloud": "Sincronizza con iCloud",
            "last_icloud_activity": "Ultima attività iCloud: %@",
            "sync_now": "Sincronizza ora",
            "sync_pending": "Sincronizzazione in corso…",
            "spread_word": "Condividi",
            "share_app": "Condividi app",
            "rate_app": "Valuta l'app",
            "support": "Supporto",
            "privacy_policy": "Informativa sulla privacy",
            "terms_of_use": "Termini di servizio",
            "contact_support": "Contatta supporto",
            "feedback": "Feedback",
            "about": "Informazioni",
            "version": "Versione",
            "tagline": "E-Sign PDF & Gestione Documenti",
            "all_features_ready": "Tutte le funzioni sbloccate",
            "my_signatures": "Le mie firme",
            "create_signature": "Crea firma"
        ],
        .pt: [
            "home": "Início",
            "history": "Histórico",
            "settings": "Ajustes",
            "signatures": "Assinaturas",
            "new_signature": "Nova assinatura",
            "save": "Salvar",
            "cancel": "Cancelar",
            "done": "Concluído",
            "close": "Fechar",
            "delete": "Excluir",
            "clear": "Limpar",
            "undo": "Desfazer",
            "edit": "Editar",
            "rename": "Renomear",
            "search": "Buscar",
            "apply": "Aplicar",
            "skip": "Pular",
            "continue": "Continuar",
            "get_started": "Começar",
            "error": "Erro",
            "ok": "OK",
            "hello": "Olá",
            "home_subtitle": "Importe um PDF e assine em segundos.",
            "search_signed_docs": "Buscar documentos assinados",
            "see_all": "Ver tudo",
            "add_new_signature": "Adicionar nova assinatura",
            "recent_signed": "Assinados recentemente",
            "recent": "Recentes",
            "see_more": "Ver mais",
            "no_signed_docs": "Nenhum documento assinado",
            "sign_first_doc": "Assine seu primeiro documento para vê-lo aqui.",
            "quick_sign_banner_title": "Assinatura rápida",
            "quick_sign_banner_subtitle": "Selecione um PDF de Arquivos para assinar",
            "import_pdf": "Importar PDF",
            "draw": "Desenhar",
            "type": "Digitar",
            "scan_photo": "Foto / Escanear",
            "signature_name": "Nome da assinatura",
            "signature_color": "Cor da assinatura",
            "stroke_size": "Espessura do traço",
            "type_your_signature": "Digite seu nome ou iniciais",
            "choose_font_style": "Estilo de fonte",
            "pick_from_photos": "Fotos",
            "take_photo": "Tirar foto",
            "remove_background": "Remover fundo",
            "bg_removed_auto": "Assinatura transparente limpa",
            "bg_sensitivity": "Sensibilidade",
            "original_photo": "Original",
            "transparent_signature": "Tinta isolada",
            "ink_color": "Cor da tinta",
            "no_signatures_yet": "Nenhuma assinatura",
            "create_signature_desc": "Toque no '+' acima para criar uma assinatura.",
            "choose_signature": "Escolher assinatura",
            "choose_signature_picker": "Assinatura",
            "rename_signature": "Renomear assinatura",
            "rename_signature_desc": "Dê um nome para esta assinatura.",
            "sign_pdf": "Assinar PDF",
            "page_x_of_y": "Página %d / %d",
            "undo_last": "Desfazer último",
            "apply_to_page": "Aplicar à página",
            "signature_size": "Tamanho",
            "signature_size_label": "Tamanho",
            "resize": "Redimensionar",
            "resize_hint": "Arraste o canto ou aperte para redimensionar",
            "document_title": "Título do documento assinado",
            "save_signed_pdf": "Salvar PDF assinado",
            "saving": "Salvando…",
            "open_preview": "Abrir pré-visualização",
            "signing_instructions": "Posicione a assinatura e toque em Aplicar.",
            "search_signed_pdfs": "Buscar PDFs assinados",
            "no_history_yet": "Sem histórico ainda",
            "history_empty_subtitle": "Documentos assinados aparecerão aqui.",
            "delete_pdf_title": "Excluir PDF assinado?",
            "delete_pdf_message": "Esta ação não pode ser desfeita.",
            "pages": "páginas",
            "page": "página",
            "share": "Compartilhar",
            "appearance": "Aparência",
            "theme_system": "Sistema",
            "theme_light": "Claro",
            "theme_dark": "Escuro",
            "preferences": "Preferências",
            "language": "Idioma",
            "select_language": "Selecionar idioma",
            "search_language": "Buscar idioma",
            "icloud_library": "Biblioteca do iCloud",
            "sync_with_icloud": "Sincronizar com o iCloud",
            "last_icloud_activity": "Última atividade no iCloud: %@",
            "sync_now": "Sincronizar agora",
            "sync_pending": "Sincronização pendente…",
            "spread_word": "Divulgar",
            "share_app": "Compartilhar aplicativo",
            "rate_app": "Avaliar aplicativo",
            "support": "Suporte",
            "privacy_policy": "Política de Privacidade",
            "terms_of_use": "Termos de Uso",
            "contact_support": "Contatar suporte",
            "feedback": "Comentários",
            "about": "Sobre",
            "version": "Versão",
            "tagline": "E-Sign PDF e Gerenciador de Documentos",
            "all_features_ready": "Todos os recursos liberados",
            "my_signatures": "Minhas assinaturas",
            "create_signature": "Criar assinatura"
        ],
        .ja: [
            "home": "ホーム",
            "history": "履歴",
            "settings": "設定",
            "signatures": "署名一覧",
            "new_signature": "新しい署名",
            "save": "保存",
            "cancel": "キャンセル",
            "done": "完了",
            "close": "閉じる",
            "delete": "削除",
            "clear": "クリア",
            "undo": "元に戻す",
            "edit": "編集",
            "rename": "名前変更",
            "search": "検索",
            "apply": "適用",
            "skip": "スキップ",
            "continue": "次へ",
            "get_started": "始める",
            "error": "エラー",
            "ok": "OK",
            "hello": "こんにちは",
            "home_subtitle": "PDFを読み込んで素早く署名できます。",
            "search_signed_docs": "署名済みドキュメントを検索",
            "see_all": "すべて見る",
            "add_new_signature": "署名を追加",
            "recent_signed": "最近署名したファイル",
            "recent": "最近",
            "see_more": "もっと見る",
            "no_signed_docs": "署名済みドキュメントはありません",
            "sign_first_doc": "最初のドキュメントに署名してみましょう。",
            "quick_sign_banner_title": "クイック署名",
            "quick_sign_banner_subtitle": "ファイルからPDFを選択して署名",
            "import_pdf": "PDFを読み込む",
            "draw": "手書き",
            "type": "テキスト",
            "scan_photo": "写真 / スキャン",
            "signature_name": "署名名",
            "signature_color": "署名の色",
            "stroke_size": "ペンの太さ",
            "type_your_signature": "名前やイニシャルを入力",
            "choose_font_style": "フォントスタイル",
            "pick_from_photos": "写真から選択",
            "take_photo": "写真を撮影",
            "remove_background": "背景を自動削除",
            "bg_removed_auto": "背景を切り抜いた透明な署名",
            "bg_sensitivity": "感度",
            "original_photo": "元画像",
            "transparent_signature": "インクのみ抽出",
            "ink_color": "インクの色",
            "no_signatures_yet": "署名がまだありません",
            "create_signature_desc": "上の「+」ボタンから作成できます。",
            "choose_signature": "署名を選択",
            "choose_signature_picker": "署名",
            "rename_signature": "署名名を変更",
            "rename_signature_desc": "分かりやすい名前を入力してください。",
            "sign_pdf": "PDFに署名",
            "page_x_of_y": "ページ %d / %d",
            "undo_last": "1つ戻す",
            "apply_to_page": "ページに適用",
            "signature_size": "サイズ",
            "signature_size_label": "サイズ",
            "resize": "サイズ変更",
            "resize_hint": "角をドラッグまたはピンチしてサイズ変更",
            "document_title": "署名済みドキュメント名",
            "save_signed_pdf": "署名済みPDFを保存",
            "saving": "保存中…",
            "open_preview": "プレビューを開く",
            "signing_instructions": "署名を配置し、「ページに適用」をタップして固定します。",
            "search_signed_pdfs": "署名済みPDFを検索",
            "no_history_yet": "履歴はありません",
            "history_empty_subtitle": "署名したドキュメントがここに表示されます。",
            "delete_pdf_title": "署名済みPDFを削除しますか？",
            "delete_pdf_message": "この操作は取り消せません。",
            "pages": "ページ",
            "page": "ページ",
            "share": "共有",
            "appearance": "外観",
            "theme_system": "システム",
            "theme_light": "ライト",
            "theme_dark": "ダーク",
            "preferences": "一般設定",
            "language": "言語",
            "select_language": "言語を選択",
            "search_language": "言語を検索",
            "icloud_library": "iCloudライブラリ",
            "sync_with_icloud": "iCloudと同期",
            "last_icloud_activity": "最終iCloud同期: %@",
            "sync_now": "今すぐ同期",
            "sync_pending": "同期保留中…",
            "spread_word": "シェア",
            "share_app": "アプリを共有",
            "rate_app": "アプリを評価",
            "support": "サポート",
            "privacy_policy": "プライバシーポリシー",
            "terms_of_use": "利用規約",
            "contact_support": "サポートへ連絡",
            "feedback": "フィードバック",
            "about": "情報",
            "version": "バージョン",
            "tagline": "E-Sign PDF & ドキュメント管理",
            "all_features_ready": "すべての機能が利用可能",
            "my_signatures": "マイ署名",
            "create_signature": "署名を作成"
        ],
        .zhHans: [
            "home": "首页",
            "history": "历史记录",
            "settings": "设置",
            "signatures": "签名库",
            "new_signature": "新建签名",
            "save": "保存",
            "cancel": "取消",
            "done": "完成",
            "close": "关闭",
            "delete": "删除",
            "clear": "清除",
            "undo": "撤销",
            "edit": "编辑",
            "rename": "重命名",
            "search": "搜索",
            "apply": "应用",
            "skip": "跳过",
            "continue": "继续",
            "get_started": "立即开始",
            "error": "错误",
            "ok": "确定",
            "hello": "您好",
            "home_subtitle": "快速导入PDF并签署文档。",
            "search_signed_docs": "搜索已签名的文档",
            "see_all": "查看全部",
            "add_new_signature": "添加新签名",
            "recent_signed": "最近签名",
            "recent": "最近",
            "see_more": "查看更多",
            "no_signed_docs": "暂无已签名文档",
            "sign_first_doc": "签署您的第一份文档即可在此查看。",
            "quick_sign_banner_title": "快捷签署",
            "quick_sign_banner_subtitle": "从文件选择PDF即可签署",
            "import_pdf": "导入PDF",
            "draw": "手绘",
            "type": "键盘输入",
            "scan_photo": "照片 / 扫描",
            "signature_name": "签名名称",
            "signature_color": "签名颜色",
            "stroke_size": "线条粗细",
            "type_your_signature": "输入您的姓名或缩写",
            "choose_font_style": "字体风格",
            "pick_from_photos": "相册导入",
            "take_photo": "拍照扫描",
            "remove_background": "一键去除背景",
            "bg_removed_auto": "清晰透明底签名",
            "bg_sensitivity": "识别灵敏度",
            "original_photo": "原图",
            "transparent_signature": "提取笔迹",
            "ink_color": "笔迹颜色",
            "no_signatures_yet": "暂无签名",
            "create_signature_desc": "点击右上角'+'即可创建新签名。",
            "choose_signature": "选择签名",
            "choose_signature_picker": "签名",
            "rename_signature": "重命名签名",
            "rename_signature_desc": "为该签名指定一个便于识别的名称。",
            "sign_pdf": "签署PDF",
            "page_x_of_y": "第 %d / %d 页",
            "undo_last": "撤销上一步",
            "apply_to_page": "应用到当前页",
            "signature_size": "大小",
            "signature_size_label": "大小",
            "resize": "调整大小",
            "resize_hint": "拖动角标或双指捏合以调整大小",
            "document_title": "签名文档标题",
            "save_signed_pdf": "保存签署后的PDF",
            "saving": "保存中…",
            "open_preview": "打开预览",
            "signing_instructions": "拖动签名调整位置，然后点击“应用到当前页”。",
            "search_signed_pdfs": "搜索已签署PDF",
            "no_history_yet": "暂无历史记录",
            "history_empty_subtitle": "已签署的文档将清晰展示在时间线中。",
            "delete_pdf_title": "删除已签署PDF？",
            "delete_pdf_message": "此操作无法撤销。",
            "pages": "页",
            "page": "页",
            "share": "分享",
            "appearance": "外观",
            "theme_system": "跟随系统",
            "theme_light": "浅色",
            "theme_dark": "深色",
            "preferences": "偏好设置",
            "language": "语言",
            "select_language": "选择语言",
            "search_language": "搜索语言",
            "icloud_library": "iCloud文档库",
            "sync_with_icloud": "同步至iCloud",
            "last_icloud_activity": "上次iCloud同步: %@",
            "sync_now": "立即同步",
            "sync_pending": "正在同步…",
            "spread_word": "分享推广",
            "share_app": "分享应用",
            "rate_app": "评价应用",
            "support": "帮助与支持",
            "privacy_policy": "隐私政策",
            "terms_of_use": "服务条款",
            "contact_support": "联系技术支持",
            "feedback": "问题与反馈",
            "about": "关于",
            "version": "版本",
            "tagline": "E-Sign PDF 电子签名与文档管理",
            "all_features_ready": "全部功能已就绪",
            "my_signatures": "我的签名",
            "create_signature": "创建签名"
        ],
        .ar: [
            "home": "الرئيسية",
            "history": "السجل",
            "settings": "الإعدادات",
            "signatures": "التواقيع",
            "new_signature": "توقيع جديد",
            "save": "حفظ",
            "cancel": "إلغاء",
            "done": "تم",
            "close": "إغلاق",
            "delete": "حذف",
            "clear": "مسح",
            "undo": "تراجع",
            "edit": "تعديل",
            "rename": "إعادة تسمية",
            "search": "بحث",
            "apply": "تطبيق",
            "skip": "تخطي",
            "continue": "متابعة",
            "get_started": "ابدأ الآن",
            "error": "خطأ",
            "ok": "حسناً",
            "hello": "مرحباً",
            "home_subtitle": "استورد ملف PDF ووقّع عليه في ثوانٍ.",
            "search_signed_docs": "بحث في المستندات الموقعة",
            "see_all": "عرض الكل",
            "add_new_signature": "إضافة توقيع جديد",
            "recent_signed": "الموقعة مؤخراً",
            "recent": "الأخيرة",
            "see_more": "المزيد",
            "no_signed_docs": "لا توجد مستندات موقعة بعد",
            "sign_first_doc": "وقّع مستندك الأول لتجده هنا.",
            "quick_sign_banner_title": "توقيع سريع",
            "quick_sign_banner_subtitle": "اختر ملف PDF من الملفات لتوقيعه",
            "import_pdf": "استيراد PDF",
            "draw": "رسم",
            "type": "كتابة",
            "scan_photo": "صورة / مسح",
            "signature_name": "اسم التوقيع",
            "signature_color": "لون التوقيع",
            "stroke_size": "حجم الخط",
            "type_your_signature": "اكتب اسمك أو حروفك الأولى",
            "choose_font_style": "نوع الخط",
            "pick_from_photos": "مكتبة الصور",
            "take_photo": "التقاط صورة",
            "remove_background": "إزالة الخلفية",
            "bg_removed_auto": "توقيع شفاف ونظيف",
            "bg_sensitivity": "الحساسية",
            "original_photo": "الأصلية",
            "transparent_signature": "حبر نقي",
            "ink_color": "لون الحبر",
            "no_signatures_yet": "لا توجد تواقيع بعد",
            "create_signature_desc": "اضغط على '+' أعلاه لإنشاء توقيع.",
            "choose_signature": "اختيار توقيع",
            "choose_signature_picker": "توقيع",
            "rename_signature": "إعادة تسمية التوقيع",
            "rename_signature_desc": "اختر اسماً مميزاً لهذا التوقيع.",
            "sign_pdf": "توقيع PDF",
            "page_x_of_y": "صفحة %d / %d",
            "undo_last": "تراجع عن الأخير",
            "apply_to_page": "تطبيق على الصفحة",
            "signature_size": "الحجم",
            "signature_size_label": "الحجم",
            "resize": "تغيير الحجم",
            "resize_hint": "اسحب الزاوية أو قرّب بإصبعيك لتغيير الحجم",
            "document_title": "عنوان المستند الموقع",
            "save_signed_pdf": "حفظ ملف PDF الموقع",
            "saving": "جارٍ الحفظ…",
            "open_preview": "فتح المعاينة",
            "signing_instructions": "اضبط مكان التوقيع ثم اضغط تطبيق على الصفحة للتثبيت.",
            "search_signed_pdfs": "بحث في ملفات PDF الموقعة",
            "no_history_yet": "لا يوجد سجل حتى الآن",
            "history_empty_subtitle": "ستظهر مستنداتك الموقعة هنا.",
            "delete_pdf_title": "حذف ملف PDF الموقع؟",
            "delete_pdf_message": "لا يمكن التراجع عن هذا الإجراء.",
            "pages": "صفحات",
            "page": "صفحة",
            "share": "مشاركة",
            "appearance": "المظهر",
            "theme_system": "تلقائي",
            "theme_light": "فاتح",
            "theme_dark": "داكن",
            "preferences": "التفضيلات",
            "language": "اللغة",
            "select_language": "اختر اللغة",
            "search_language": "البحث عن لغة",
            "icloud_library": "مكتبة iCloud",
            "sync_with_icloud": "مزامنة المكتبة مع iCloud",
            "last_icloud_activity": "آخر نشاط لـ iCloud: %@",
            "sync_now": "مزامنة الآن",
            "sync_pending": "المزامنة معلقة…",
            "spread_word": "شارك التطبيق",
            "share_app": "مشاركة التطبيق",
            "rate_app": "تقييم التطبيق",
            "support": "الدعم والمساعدة",
            "privacy_policy": "سياسة الخصوصية",
            "terms_of_use": "شروط الاستخدام",
            "contact_support": "تواصل مع الدعم",
            "feedback": "الآراء والملاحظات",
            "about": "حول التطبيق",
            "version": "الإصدار",
            "tagline": "E-Sign PDF وإدارة المستندات",
            "all_features_ready": "جميع الميزات متاحة",
            "my_signatures": "تواقيعي",
            "create_signature": "إنشاء توقيع"
        ],
        .hi: [
            "home": "होम",
            "history": "इतिहास",
            "settings": "सेटिंग्स",
            "signatures": "हस्ताक्षर",
            "new_signature": "नया हस्ताक्षर",
            "save": "सहेजें",
            "cancel": "रद्द करें",
            "done": "पूर्ण",
            "close": "बंद करें",
            "delete": "हटाएं",
            "clear": "साफ़ करें",
            "undo": "पूर्ववत करें",
            "edit": "संपादित करें",
            "rename": "नाम बदलें",
            "search": "खोजें",
            "apply": "लागू करें",
            "skip": "छोड़ें",
            "continue": "जारी रखें",
            "get_started": "शुरू करें",
            "error": "त्रुटि",
            "ok": "ठीक है",
            "hello": "नमस्ते",
            "home_subtitle": "PDF आयात करें और कुछ ही सेकंड में हस्ताक्षर करें।",
            "search_signed_docs": "हस्ताक्षरित दस्तावेज़ खोजें",
            "see_all": "सभी देखें",
            "add_new_signature": "नया हस्ताक्षर जोड़ें",
            "recent_signed": "हाल ही में हस्ताक्षरित",
            "recent": "हाल के",
            "see_more": "और देखें",
            "no_signed_docs": "अभी तक कोई हस्ताक्षरित दस्तावेज़ नहीं है",
            "sign_first_doc": "यहां देखने के लिए अपना पहला दस्तावेज़ हस्ताक्षर करें।",
            "quick_sign_banner_title": "त्वरित हस्ताक्षर",
            "quick_sign_banner_subtitle": "हस्ताक्षर करने के लिए फ़ाइलों से PDF चुनें",
            "import_pdf": "PDF आयात करें",
            "draw": "बनाएं",
            "type": "टाइप करें",
            "scan_photo": "फोटो / स्कैन",
            "signature_name": "हस्ताक्षर का नाम",
            "signature_color": "हस्ताक्षर का रंग",
            "stroke_size": "स्ट्रोक का आकार",
            "type_your_signature": "अपना नाम या आद्याक्षर लिखें",
            "choose_font_style": "फ़ॉन्ट शैली",
            "pick_from_photos": "फ़ोटो गैलरी",
            "take_photo": "फ़ोटो लें",
            "remove_background": "पृष्ठभूमि हटाएं",
            "bg_removed_auto": "पारदर्शी साफ़ हस्ताक्षर",
            "bg_sensitivity": "संवेदनशीलता",
            "original_photo": "मूल फ़ोटो",
            "transparent_signature": "केवल स्याही",
            "ink_color": "स्याही का रंग",
            "no_signatures_yet": "अभी कोई हस्ताक्षर नहीं है",
            "create_signature_desc": "हस्ताक्षर बनाने के लिए ऊपर '+' पर टैप करें।",
            "choose_signature": "हस्ताक्षर चुनें",
            "choose_signature_picker": "हस्ताक्षर",
            "rename_signature": "हस्ताक्षर का नाम बदलें",
            "rename_signature_desc": "इस हस्ताक्षर को एक यादगार नाम दें।",
            "sign_pdf": "PDF पर हस्ताक्षर करें",
            "page_x_of_y": "पृष्ठ %d / %d",
            "undo_last": "अंतिम पूर्ववत करें",
            "apply_to_page": "पृष्ठ पर लागू करें",
            "signature_size": "आकार",
            "signature_size_label": "आकार",
            "resize": "आकार बदलें",
            "resize_hint": "कोने को खींचें या आकार बदलने के लिए पिंच करें",
            "document_title": "हस्ताक्षरित दस्तावेज़ का शीर्षक",
            "save_signed_pdf": "हस्ताक्षरित PDF सहेजें",
            "saving": "सहेजा जा रहा है…",
            "open_preview": "पूर्वावलोकन खोलें",
            "signing_instructions": "हस्ताक्षर की स्थिति सेट करें और लॉक करने के लिए लागू करें पर टैप करें।",
            "search_signed_pdfs": "हस्ताक्षरित PDF खोजें",
            "no_history_yet": "अभी कोई इतिहास नहीं",
            "history_empty_subtitle": "आपके हस्ताक्षरित दस्तावेज़ यहां दिखाई देंगे।",
            "delete_pdf_title": "हस्ताक्षरित PDF हटाएं?",
            "delete_pdf_message": "यह क्रिया पूर्ववत नहीं की जा सकती।",
            "pages": "पृष्ठ",
            "page": "पृष्ठ",
            "share": "साझा करें",
            "appearance": "दिखावट",
            "theme_system": "सिस्टम",
            "theme_light": "लाइट",
            "theme_dark": "डार्क",
            "preferences": "प्राथमिकताएं",
            "language": "भाषा",
            "select_language": "भाषा चुनें",
            "search_language": "भाषा खोजें",
            "icloud_library": "iCloud लाइब्रेरी",
            "sync_with_icloud": "iCloud के साथ सिंक करें",
            "last_icloud_activity": "अंतिम iCloud गतिविधि: %@",
            "sync_now": "अभी सिंक करें",
            "sync_pending": "सिंक लंबित है…",
            "spread_word": "साझा करें",
            "share_app": "ऐप साझा करें",
            "rate_app": "ऐप को रेट करें",
            "support": "सहायता",
            "privacy_policy": "गोपनीयता नीति",
            "terms_of_use": "उपयोग की शर्तें",
            "contact_support": "सहायता से संपर्क करें",
            "feedback": "प्रतिक्रिया",
            "about": "के बारे में",
            "version": "संस्करण",
            "tagline": "E-Sign PDF और दस्तावेज़ प्रबंधक",
            "all_features_ready": "सभी सुविधाएं उपलब्ध",
            "my_signatures": "मेरे हस्ताक्षर",
            "create_signature": "हस्ताक्षर बनाएं"
        ]
    ]
}
